version: "3.8"

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      TZ:                  ${TZ}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    env_file:
      - .env
    environment:
      PMA_HOST:     ${DB_HOST}
      UPLOAD_LIMIT: 500M
    ports:
      - "8082:80"

  php:
    build: ./server/images
    env_file:
      - .env
    depends_on:
      - mysql
    environment:
      DB_HOST:          ${DB_HOST}
      DB_DATABASE:      ${DB_DATABASE}
      DB_USERNAME:      ${DB_USERNAME}
      DB_PASSWORD:      ${DB_PASSWORD}
      API_SECRET:       ${API_SECRET}
      REDIS_SERVERS:    ${REDIS_SERVERS}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
      ENCRYPTION_KEY:   ${ENCRYPTION_KEY}
    volumes:
      - ./server/www:/var/www
      - ./server/www/erp/certs:/etc/ssl/certs:rw
      - ./server/images/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./tmp/nomenclature_images:/tmp/nomenclature_images

  nginx:
    image: nginx:latest
    env_file:
      - .env
    depends_on:
      - php
    environment:
      DB_HOST:     ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server/hosts:/etc/nginx/conf.d:ro
      - ./server/www:/var/www
      - ./server/logs:/var/log/nginx

  react-app:
    build:
      context: ./client/react-app
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - nginx
      - php
    environment:
      WATCHPACK_POLLING: ${WATCHPACK_POLLING}
      NODE_ENV:         ${NODE_ENV}
      REACT_APP_PATH:   ${REACT_APP_PATH}
    ports:
      - "3000:3000"
    volumes:
      - ./client/react-app:/app
      - /app/node_modules

# ← This section must not be indented under "services":
volumes:
  mysql_data:
  rabbitmq_data:
